//
// Created by Andrew Lvovsky on 6/8/17.
//

#ifndef SQL_DATABASE_PROJECT_CONSTANTS_H
#define SQL_DATABASE_PROJECT_CONSTANTS_H

const int COLUMN_WIDTH = 15;

#endif //SQL_DATABASE_PROJECT_CONSTANTS_H
